name: Run abaplint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  abaplint:
    name: abaplint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run abaplint
        run: |
          npm -g install abaplint
          abaplint
